CREATE TABLE IF NOT EXISTS ai_conversation (
 id VARCHAR(36) PRIMARY KEY, user_id BIGINT NOT NULL, title VARCHAR(200) NOT NULL,
 summary MEDIUMTEXT, summary_through BIGINT NOT NULL DEFAULT 0, revision BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX ix_conversation_owner (user_id,updated_at)
);
CREATE TABLE IF NOT EXISTS ai_message (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, conversation_id VARCHAR(36) NOT NULL, user_id BIGINT NOT NULL,
 turn_id VARCHAR(36) NOT NULL, role VARCHAR(20) NOT NULL, content MEDIUMTEXT NOT NULL, sources_json MEDIUMTEXT,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX ix_message_conversation(conversation_id,id)
);
CREATE TABLE IF NOT EXISTS ai_memory_job (
 id VARCHAR(36) PRIMARY KEY, user_id BIGINT NOT NULL, conversation_id VARCHAR(36) NOT NULL,
 content MEDIUMTEXT NOT NULL, generation BIGINT NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', attempts INT NOT NULL DEFAULT 0,
 error_code VARCHAR(100), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 INDEX ix_memory_job_state(status,updated_at)
);
CREATE TABLE IF NOT EXISTS ai_memory (
 id VARCHAR(36) PRIMARY KEY, user_id BIGINT NOT NULL, entity VARCHAR(200) NOT NULL, attribute_name VARCHAR(100) NOT NULL,
 fact_value VARCHAR(1000) NOT NULL, content TEXT NOT NULL, source VARCHAR(36) NOT NULL, confidence DOUBLE NOT NULL,
 version BIGINT NOT NULL DEFAULT 1, deleted BOOLEAN NOT NULL DEFAULT FALSE, projected BOOLEAN NOT NULL DEFAULT FALSE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_memory_fact(user_id,entity,attribute_name), INDEX ix_memory_owner(user_id,deleted)
);
CREATE TABLE IF NOT EXISTS ai_memory_preference (user_id BIGINT PRIMARY KEY, enabled BOOLEAN NOT NULL DEFAULT TRUE, generation BIGINT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS ai_memory_history (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, memory_id VARCHAR(36) NOT NULL, user_id BIGINT NOT NULL,
 content TEXT NOT NULL, version BIGINT NOT NULL, source VARCHAR(36) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS knowledge_document (
 id BIGINT PRIMARY KEY, product_id BIGINT NOT NULL, title VARCHAR(250) NOT NULL, content_hash VARCHAR(64) NOT NULL,
 original_text MEDIUMTEXT NOT NULL, version INT NOT NULL DEFAULT 1, status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
 error_code VARCHAR(100), chunk_count INT NOT NULL DEFAULT 0, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS knowledge_chunk (
 id BIGINT PRIMARY KEY, document_id BIGINT NOT NULL, product_id BIGINT NOT NULL, title VARCHAR(250) NOT NULL,
 heading VARCHAR(250) NOT NULL, content MEDIUMTEXT NOT NULL, start_offset INT NOT NULL, end_offset INT NOT NULL,
 embedding_json MEDIUMTEXT, active BOOLEAN NOT NULL DEFAULT TRUE,
 INDEX ix_chunk_document(document_id,active)
);
